In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#Chapter1 토큰화

In [4]:
#문제 1. 토큰화 패키지를 사용하여 토큰화를 해봅시다.

In [5]:
#문제 1-1. 다음 sentence를 문장 단위로 구분하는 문장 토큰화를 실행하세요.(nltk)

In [55]:
import nltk
import konlpy

sentence1 = 'One of the essential things in the life of a human being is communication. We need to communicate with other human beings to deliver information, express our emotions, present ideas, and much more. The key to communication is language.'
result_sent1 = nltk.sent_tokenize(sentence1)
print(result_sent1)

['One of the essential things in the life of a human being is communication.', 'We need to communicate with other human beings to deliver information, express our emotions, present ideas, and much more.', 'The key to communication is language.']


In [19]:
#문제 1-2. 다음 sentence를 단어 단위로 토큰화해주세요.(nltk)

In [20]:
from nltk.tokenize import SpaceTokenizer
from nltk.tokenize import word_tokenize

sentence2 = 'We need to communicate with other human beings to deliver information, express our emotions, present ideas, and much more.'
sentence3 = 'The price\t of burger \nin BurgerKing is Rs.36.\n'

In [21]:
space_tokenizer = SpaceTokenizer()
print(space_tokenizer.tokenize(sentence2))

space_tokenizer = SpaceTokenizer()
print(space_tokenizer.tokenize(sentence3))

['We', 'need', 'to', 'communicate', 'with', 'other', 'human', 'beings', 'to', 'deliver', 'information,', 'express', 'our', 'emotions,', 'present', 'ideas,', 'and', 'much', 'more.']
['The', 'price\t', 'of', 'burger', '\nin', 'BurgerKing', 'is', 'Rs.36.\n']


In [22]:
# SpaceTokenizer는 문장에 들어있는 \n 등의 제어문자 등을 인식하지 않고 단순히 공백을 기준으로 문장을 토큰화한다.
# 또한 마침표 등의 문장부호도 공백 없이 입력되기 때문에 따로 토큰화되지 않는다.

In [23]:
result_sent2 = word_tokenize(sentence2)
print(result_sent2)
result_sent3 = word_tokenize(sentence3)
print(result_sent3)

['We', 'need', 'to', 'communicate', 'with', 'other', 'human', 'beings', 'to', 'deliver', 'information', ',', 'express', 'our', 'emotions', ',', 'present', 'ideas', ',', 'and', 'much', 'more', '.']
['The', 'price', 'of', 'burger', 'in', 'BurgerKing', 'is', 'Rs.36', '.']


In [24]:
#반면 word_tokenize는 제어문자나 문장부호를 구분하여 토큰화하기 때문에 가장 많이 사용된다.

In [25]:
#문제 1-3. Konlpy(okt) 라이브러리를 사용하여 ‘1-3.txt’ 파일에서 50문장을 골라 한글 형태소 분석을 진행해주세요.

In [2]:
pd.set_option('display.max_colwidth', 1)
from konlpy.tag import Okt

txt1_3 = pd.read_csv('C:/Users/mrg07/Desktop/99shimshim/SKKU/PSAT/주제분석/week2/week2_package/1-3.txt', sep = "\t")



In [3]:
txt1_3 = txt1_3['document'].sample(50) #댓글 물타기로 인한 편향을 방지하기 위해 random한 50개를 가져옴.
txt1_3

97936     대단한 영화다 보는 내내 한순간도 한눈팔지못하게한 영화다.감히 이 영화는 타인의 추종을 불허하는 내 손가락에 꼽힐정도의 영화다                                                                     
29063     볼만은 하다. 하지만 전체적인 스토리로 봤을때 이어지는 내용이 없다. 사람들이 이해할수 있는 내용으로 시작을 해야되는데 이해되는 부분이 많이 없다. 반전이 있어 스릴이 잇었지만 전체적인 내용으로 봐서는 이 영화의 중심이 없는거 같다.         
92791     차마 욕은 쓸수 없고..한숨만 나온다. 이 영화를 봤다는게..                                                                                                         
90600     파격조차 느껴지지 않는 광신도들                                                                                                                          
93980     영화로 부린 마법                                                                                                                                  
87680     말도 안되는 축구기술이며, 스토리또한 이해가 잘 되진 않지만... 이렇게 창의력있는 축구 만화는 처음이다                                                                                 
47058     많은생각을해주게 하는영화                                                                             

In [5]:
for i, document in enumerate(txt1_3):
    okt = Okt()
    clean_words = []
    for word in okt.pos(document, norm=True, stem=True): #어간 추출
        if word[1] not in ['Josa', 'Eomi', 'Punctuation']: #조사, 어미, 구두점 제외 
            clean_words.append(word[0])
    print(clean_words) #['스토리', '진짜', '너무', '노잼']

['대단하다', '영화', '보다', '내내', '한순간', '한눈팔다', '하다', '영화', '감히', '이', '영화', '타인', '추종', '불허', '하다', '내', '손가락', '꼽히다', '정도', '영화']
['볼', '하다', '하지만', '전체', '적', '스토리', '보다', '때', '이어지다', '내용', '없다', '사람', '들', '이해', '하다', '있다', '내용', '시작', '하다', '되다', '이해', '되다', '부분', '많이', '없다', '반전', '있다', '스릴', '잇다', '전체', '적', '내용', '보다', '서다', '이', '영화', '중심', '없다', '같다']
['차마', '욕', '쓸다', '없다', '한숨', '나오다', '이', '영화', '보다']
['파격', '느껴지다', '않다', '광신도', '들']
['영화로', '부리다', '마법']
['말', '안되다', '축구', '기술', '스토리', '또한', '이해', '자다', '되다', '않다', '이렇게', '창의력', '있다', '축구', '만화', '처음']
['많다', '생각', '해주다', '하다', '영화']
['유사하다', '영화', '아', '임', '낫', '스', '케어드']
['007', '시리즈', '중', '최고', '생각', '하다', '평점', '왜', '이렇게', '낮다', '박평', '식', '8', '점', '준', '영화']
['딸내미', '귀엽다', '단역', '들', '화려하다', '그', '뿐']
['톰크루즈', '리즈시절', '물론', '연기력', '호프', '甲', '중', '甲']
['최악']
['히스', '레저', '팬', '일부러', '보다', '내용', '자체', '과', '시대', '적', '배경', '신선하다', '재밌다', '뻔하다', '결말', '전체', '적', '유쾌하다', '승화', '시키다', '한', '영화']
['이영화', '구려', '존나', 'ㅋ']
['

In [ ]:
#문제 2. nltk 라이브러리를 사용하여 토큰화 후 다음 문장에서 불용어 제거를 해보세요.

In [8]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
from konlpy.tag import Okt

sent2 = "We need a common language to communicate, which both ends of the conversation can understand."

stop_words_list = stopwords.words('english')
stop_words = set(stopwords.words('english'))
word_tokens = word_tokenize(sent2)

In [16]:
result = []

for word in word_tokens: 
    if word not in stop_words: 
        result.append(word) 

print('불용어 제거 전 :',word_tokens) 
print('불용어 개수 :', len(stop_words_list))
print('불용어 제거 후 :',result)
print('불용어 10개 출력 :',stop_words_list[:10])

불용어 제거 전 : ['We', 'need', 'a', 'common', 'language', 'to', 'communicate', ',', 'which', 'both', 'ends', 'of', 'the', 'conversation', 'can', 'understand', '.']
불용어 개수 : 179
불용어 제거 후 : ['We', 'need', 'common', 'language', 'communicate', ',', 'ends', 'conversation', 'understand', '.']
불용어 10개 출력 : ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


In [ ]:
#문제 3. nltk 라이브러리에서는 어간 추출 알고리즘 중 하나인 포터 알고리즘을 제공합니다.
#여러 단어들을 넣어보며 원형을 잘 보존하는지 확인해보세요.

In [23]:
from nltk import PorterStemmer, word_tokenize

porter = PorterStemmer()

print(porter.stem('plays'),porter.stem('played'),porter.stem('playing'))
print(porter.stem('laughs'),porter.stem('laughed'),porter.stem('laughing'))
print(porter.stem('happier'),porter.stem('happiest'))

print(porter.stem('going'), porter.stem('goes'), porter.stem('gone'), porter.stem('went'))
print(porter.stem('eat'), porter.stem('ate'), porter.stem('eaten'))
print(porter.stem('have'), porter.stem('had'))

#불규칙 활용 동사는 3단현, 과거형으로부터 원형 추출이 안 됨
#속도가 빠르며 차원축소에 용이함: 단어가 다양한 형태여도 원형에 대해서만 임배딩을 해주면 되니까.

play play play
laugh laugh laugh
happier happiest
go goe gone went
eat ate eaten
have had


In [108]:
#문제 4. nltk 라이브러리에는 표제어 추출 알고리즘을 제공합니다. 여러 단어들을 넣어보며 표제어를 잘 추출하는지 확인해보세요.

In [53]:
from nltk import PorterStemmer, WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

print(lemmatizer.lemmatize('flying', pos='v'))    # pos: 품사     v: verb   n: noun

print(lemmatizer.lemmatize('flies', pos='n'))    # 파리의 단수형
print(lemmatizer.lemmatize('flies', pos='v'))    # 날다의 동사원형

print(lemmatizer.lemmatize('flying', pos='v'))   # 날다의 동사원형
print(lemmatizer.lemmatize('flying', pos='n'))   # 동명사 '나는 것' 보존

#속도가 느리지만 품사를 보존하며 추출할 수 있음.
#같은 표현이라도 품사가 다른 것을 반영

fly
fly
fly
fly
flying


In [21]:
#Chapter 2 임베딩

In [22]:
#문제1. 횟수 기반 임베딩 중 하나인 CountVectorizer를 다음 코퍼스에 사용하여 얻은 결과를 배열로 변환해주세요.

In [44]:
from bs4 import BeautifulSoup
import konlpy
from sklearn.feature_extraction.text import CountVectorizer

In [50]:
corpus = ['This is the first document.', 'This is the second second document.', 'And the third one.', 'Is this the first document?', 'The last document?']

In [51]:
transformer = CountVectorizer()
transformer.fit(corpus)
corpus = transformer.transform(corpus)
print(corpus.toarray())

[[0 1 1 1 0 0 0 1 0 1]
 [0 1 0 1 0 0 2 1 0 1]
 [1 0 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 0 1 0 1]
 [0 1 0 0 1 0 0 1 0 0]]


In [26]:
#문제2. 예측 기반 임베딩인 Word2Vec를 사용하여 단어간 의미 유사도를 구해보겠습니다.
#문제2-1. ‘2-1.txt’ 파일을 불러와주세요. 파일은 소설 피터팬 원문의 일부분입니다.
#문제2-2. 파일 문장을 단어로 모두 토큰화해주세요.

#문제2-3. 토큰화된 단어를 모두 소문자로 변환하여 저장해주세요

In [70]:
import nltk
from nltk import word_tokenize
import re

f = open('C:/Users/mrg07/Desktop/99shimshim/SKKU/PSAT/주제분석/week2/week2_package/2-1.txt', encoding='utf-8')
txt2_1 = f.read()
txt2_1

token2_sent = nltk.sent_tokenize(txt2_1)
token2 = re.sub(r'[^a-zA-Z\. ]', ' ', txt2_1)
token2 = token2.split('. ')
token2 = [s.split() for s in token2_sent]
#print(token2)

print(token2[0])

token2_lower = []
for i in token2 :
    for j in range(0, len(i)):
        token2_lower.append(token2[i][j].lower())     #소문자로 변환

print(token2_lower)

['Once', 'upon', 'a', 'time', 'in', 'London,', 'the', 'darlings', 'went', 'out', 'to', 'a', 'dinner', 'party', 'leaving', 'their', 'three', 'children', 'Wendy,', 'Jhon,', 'and', 'Michael', 'at', 'home.']


TypeError: 'int' object is not iterable

In [84]:
#문제2-4. CBOW 방식으로 벡터화를 진행한 후 ‘peter’와 ‘wendy’, ‘peter’와 ‘hook’의 유사도를 각각 구해주세요. (min_count = 1, vector_size = 100, window=5)

In [85]:
import urllib.request
import zipfile
from lxml import etree
from nltk.tokenize import word_tokenize, sent_tokenize

In [86]:
print('총 샘플의 개수 : {}'.format(len(token2)))

총 샘플의 개수 : 89


In [ ]:
#https://wikidocs.net/50739

In [ ]:
#http://doc.mindscale.kr/km/unstructured/11.html

In [87]:
from gensim.models import Word2Vec
from gensim.models import KeyedVectors

model = Word2Vec(sentences = token2, vector_size=100, window=5, min_count=1)

In [90]:
model.wv.similarity('Peter', 'Wendy')

0.0064410693

In [ ]:
model.wv.similarity('Peter', 'Hook')

In [ ]:
#문제2-5. 문제 ‘2-4’를 skip-gram 방식으로 진행해주세요. 설정값도 동일합니다.

In [94]:
model = Word2Vec(sentences = token2, vector_size=100, window=5, min_count=1, sg=1)

In [95]:
model.wv.similarity('Peter', 'Wendy')

0.12741406

In [96]:
model.wv.similarity('Peter', 'Hook')

0.12661389

In [ ]:
#문제2-6. Word2Vec의 단점을 보완한 ‘FastText’ 알고리즘을 사용하여 문제 ‘2-4’를 해결해주세요.
#그리고 온라인 텍스트와 같이 오탈자가 많은 경우에 ‘FastText’가 왜 더욱 잘 작동할지 특징을 간략히만 적어주세요.

In [ ]:
#Word2Vec는 단어를 쪼개질 수 없는 단위로 생각한다면, FastText는 하나의 단어 안에도 여러 단어들이 존재하는 것으로 간주합니다. 내부 단어. 즉, 서브워드(subword)를 고려하여 학습합니다.
#Word2Vec는 학습 데이터에 존재하지 않는 단어, 즉, 모르는 단어에 대해서는 임베딩 벡터가 존재하지 않기 때문에 단어의 유사도를 계산할 수 없습니다.Word2Vec의 경우에는 등장 빈도 수가 적은 단어(rare word)에 대해서는 임베딩의 정확도가 높지 않다는 단점이 있었습니다. 참고할 수 있는 경우의 수가 적다보니 정확하게 임베딩이 되지 않는 경우입니다.
#FastText에서는 각 단어는 글자 단위 n-gram의 구성으로 취급합니다. n을 몇으로 결정하는지에 따라서 단어들이 얼마나 분리되는지 결정됩니다.
#이를 이용해서 모르는 단어(Out Of Vocabulary, OOV)에 대한 대응이 가능하고, 단어 집합 내 빈도 수가 적었던 단어(Rare Word)에 대한 대응이 가능해집니다.

#출처: https://wikidocs.net/22883

In [ ]:
#문제3. attention은 nlp 분야에서 매우 중요한 매커니즘인데, 이를 사용한 모델 중 대표적인 BERT 모델이 어떻게 토큰화부터 임베딩까지 진행하여 높은 성능을 보여주었는지 알아보겠습니다.

In [ ]:
#문제3-1. 다음 문장을 사전훈련된 bert tokenizer를 이용하여 토큰화해주세요. ‘bert-base-uncased’로 설정하여 기본 모델을 사용하겠습니다.

In [2]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-cased")

text3 = 'NLP is an interdisciplinary subfield of linguistics, computer science, and artificial intelligence'

tokenizer(text3)

{'input_ids': [101, 21239, 2101, 1110, 1126, 24568, 4841, 2427, 1104, 23213, 117, 2775, 2598, 117, 1105, 8246, 4810, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [3]:
#문제3-2. Bert는 토큰을 이용하여 문장을 구분하는데 문장 앞에는 ‘[CLS]’, 뒤에는 ‘[SEP]’ 토큰을 붙입니다.
#위의 ‘text’ 또한 두 개의 토큰을 앞뒤에 붙여 저장해주세요

In [3]:
text3 = '[CLS] NLP is an interdisciplinary subfield of linguistics, computer science, and artificial intelligence [SEP]'

In [5]:
#문제3-3. Bert는 tokenize() 함수를 사용하여 토큰화를 진행한 뒤 결과를 확인해주세요. 단어 단위로 토큰화를 한 후 알 수 없는 단어는 더 작은 단위로 분리한 것을 확인할 수 있습니다.

In [4]:
tokenized_text3 = tokenizer.tokenize(text3)
print(tokenized_text3)

['[CLS]', 'NL', '##P', 'is', 'an', 'interdisciplinary', 'sub', '##field', 'of', 'linguistics', ',', 'computer', 'science', ',', 'and', 'artificial', 'intelligence', '[SEP]']


In [7]:
#문제3-4. convert_tokens_to_ids() 함수를 사용하여 각 토큰의 인덱스를 알 수 있습니다. 결과값이 위의‘input_ids’인 것을 알 수 있습니다. 결과를 따로 저장해주세요.

In [5]:
ids = tokenizer.convert_tokens_to_ids(tokenized_text3)

In [6]:
#문제3-5. 문제에서 하나의 문장을 사용 중이기 때문에 3가지 인풋 모두 사용하지 않아도 됩니다.‘attention_mask’와 같은 리스트만 만들주세요.

In [7]:
attm = tokenizer(text3)['attention_mask']

In [8]:
#문제3-6. 문제 4-4~5에서 만든 두 가지 리스트를 텐서로 변환해주세요.

In [9]:
import torch

In [10]:
ids = torch.tensor(ids)
attm = torch.tensor(attm)

In [ ]:
#문제3-7. BertModel(bert-base-uncased, output_hidden_states = True로 설정)를 구축한 후 텐서를 넣어 결과를 확인해주세요.

In [12]:
from transformers import BertConfig, BertModel

config = BertConfig()
model = BertModel(config)

In [ ]:
#https://wikidocs.net/166799

In [13]:
model = BertModel.from_pretrained("bert-base-uncased", output_hidden_states = True)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [17]:
attm

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [40]:
model(ids)

ValueError: not enough values to unpack (expected 2, got 1)

In [ ]:
#Chapter 3 정형데이터 적용(LSTM)

In [ ]:
#문제1. ‘Modelling.csv’ 데이터를 불러온 후 구조를 파악해주세요. 이는 기업의 주가 정보 데이터입니다.

In [37]:
data3 = pd.read_csv('C:/Users/mrg07/Desktop/99shimshim/SKKU/PSAT/주제분석/week2/week2_package/Modelling.csv')
#data3.info

In [38]:
#문제2. ‘Date’ 칼럼을 datetime 형식으로 바꾼 후 ‘Date’ 칼럼을 인덱스로 설정해주세요.

In [39]:
from datetime import datetime
import warnings

datetime.strptime(data3['Date'][1], '%Y-%m-%d')

for i in range(len(data3)):
    data3['Date'][i] = datetime.strptime(data3['Date'][i], '%Y-%m-%d')

data3 = data3.set_index(keys='Date')

warnings.filterwarnings('ignore')

In [40]:
#문제3. ‘Volume’ 칼럼을 실수로 변환한 후. ‘Volume’ 칼럼을 레이블(y), 나머지를 훈련(x) 데이터로 분할해주세요.

In [41]:
data3['Volume'] = data3['Volume'].astype(float)
y = pd.DataFrame(data3['Volume'])
x = pd.DataFrame(data= data3.iloc[:,0:5])

In [42]:
#문제4. 데이터 간의 분포를 맞추기 위해 스케일링을 해보겠습니다.

In [43]:
#문제4-1. StandardScaler를 사용하여 x 데이터를, MinMaxScaler()를 사용하여 y 데이터를 스케일링해주세요.

In [44]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

std_scaler = StandardScaler()
std_scaled = std_scaler.fit_transform(x)

mm_scaler = MinMaxScaler()
mm_scaler.fit(y)
mm_scaled = mm_scaler.transform(y)

In [45]:
#문제5. x와 y데이터는 253행을 갖고 있는데 그 중 200개는 훈련 데이터셋, 나머지는 테스트 데이터셋으로 각각 분할해주세요.

In [46]:
from sklearn.model_selection import train_test_split

np.random.seed(2017)
X_train, X_test, Y_train, Y_test = train_test_split(x, y, train_size=200)

print(len(X_train), len(X_test))

200 53


In [47]:
#문제6. 데이터를 모두 텐서로 변환한 후 x 데이터를 LSTM의 입력 형태와 맞추기 위해 형태를 변경해주세요.

In [48]:
#문제6-1. Train x 데이터는 [200,1,5], test x 데이터는 [53,1,5]의 형태를 가져야 합니다.

In [49]:
from torch.utils.data import TensorDataset # 텐서데이터셋

In [51]:
X_train = X_train.values
X_test = X_test.values

X_train_tensor = torch.FloatTensor(X_train)
X_test_tensor = torch.FloatTensor(X_test)

In [52]:
X_train_tensor.shape

torch.Size([200, 5])

In [ ]:
#문제7. LSTM 모델을 class의 형태로 만들어 구축해주세요. 모델을 만들 때에는 torch.nn.Module을 상속 받아야하며, __init__, forward 함수가 필수적으로 구현되어 있어야 합니다.

In [35]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
class LSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, layer_dim, output_dim):
        super(LSTMModel, self).__init__()
        # Hidden dimensions
        self.hidden_dim = hidden_dim

        # Number of hidden layers
        self.layer_dim = layer_dim

        # Building your LSTM
        # batch_first=True causes input/output tensors to be of shape
        # (batch_dim, seq_dim, feature_dim)
        self.lstm = nn.LSTM(input_dim, hidden_dim, layer_dim, batch_first=True)

        # Readout layer
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        # Initialize hidden state with zeros
        h0 = torch.zeros(self.layer_dim, x.size(0), self.hidden_dim).requires_grad_()

        # Initialize cell state
        c0 = torch.zeros(self.layer_dim, x.size(0), self.hidden_dim).requires_grad_()

 
        # We need to detach as we are doing truncated backpropagation through time (BPTT)
        # If we don't, we'll backprop all the way to the start even after going through another batch
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        # Index hidden state of last time step
        # out.size() --> 100, 28, 100
        # out[:, -1, :] --> 100, 100 --> just want last time step hidden states! 
        out = self.fc(out[:, -1, :]) 
        # out.size() --> 100, 10
        return out

In [ ]:
input_dim = 200
hidden_dim = 2
layer_dim = 1
output_dim = 

In [ ]:
#https://www.deeplearningwizard.com/deep_learning/practical_pytorch/pytorch_lstm_neuralnetwork/

In [ ]:
죄송합니다... 바닥난 체력에 예비군을 들이부었더니 약간의 병을 얻어서... 다음주엔 건강히 해내겠습니다!